version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.4
jobs:
  build:
    machine:
      image: ubuntu-2204:2023.02.1
    steps:
      - checkout
      - aws-cli/install
      - run:
          name: Build & Push Docker Image
          command: |
            wget https://github.com/containerd/containerd/releases/download/v1.6.2/containerd-1.6.2-linux-amd64.tar.gz
            sudo tar Czxvf /usr/local containerd-1.6.2-linux-amd64.tar.gz
            wget https://raw.githubusercontent.com/containerd/containerd/main/containerd.service
            ls -al
            #sudo mv containerd.service /usr/lib/systemd/system/
            #sudo systemctl daemon-reload
            
            #sudo systemctl status containerd
        
            wget https://github.com/containerd/nerdctl/releases/download/v1.7.2/nerdctl-full-1.7.2-linux-amd64.tar.gz
            sudo tar Czxvf /usr/local nerdctl-full-1.7.2-linux-amd64.tar.gz
            nerdctl -v

            version="0.5.0"
            wget https://github.com/awslabs/soci-snapshotter/releases/download/v${version}/soci-snapshotter-${version}-linux-amd64.tar.gz
            sudo tar -C /usr/local/bin -xvf soci-snapshotter-${version}-linux-amd64.tar.gz
            sudo soci --help

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          name: build_na_amd