version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.4
  slack: circleci/slack@4.1
jobs:
  build:
    machine:
      image: ubuntu-2204:2023.02.1
    steps:
      - checkout
      - aws-cli/install
      - run:
          name: Build & Push Docker Image
          command: |
            wget https://github.com/containerd/containerd/releases/download/v1.6.2/containerd-1.6.2-linux-amd64.tar.gz
            sudo tar Czxvf /usr/local containerd-1.6.2-linux-amd64.tar.gz
            wget https://raw.githubusercontent.com/containerd/containerd/main/containerd.service
            ls -al
            wget https://github.com/containerd/nerdctl/releases/download/v1.7.2/nerdctl-full-1.7.2-linux-amd64.tar.gz
            sudo tar Czxvf /usr/local nerdctl-full-1.7.2-linux-amd64.tar.gz
            nerdctl -v

            version="0.5.0"
            wget https://github.com/awslabs/soci-snapshotter/releases/download/v${version}/soci-snapshotter-${version}-linux-amd64.tar.gz
            sudo tar -C /usr/local/bin -xvf soci-snapshotter-${version}-linux-amd64.tar.gz
            sudo soci --help

            sudo nerdctl run -it --rm alpine
            sudo nerdctl ps
            name = "master"
            age  = "18"

            if [[ name = 'master' ]] || [[ age = '18' ]]
            then
              echo "aws ecr get-login-password"
              echo "docker push"
              echo "docker"
            fi
      - slack/notify:
          debug: true
          template: basic_fail_1
          mentions: "@orbs"
          event: always
      - slack/notify:
          debug: true
          template: basic_success_1
          event: always
      - slack/notify:
          debug: true
          template: success_tagged_deploy_1
          event: always
      - slack/notify:
          debug: true
          template: basic_on_hold_1
          event: always        

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          name: build_na_amd
